### PR TITLE
Allow CSV comments

### PR DESCRIPTION
**Pull request by dbrgn**
Comments in the `urls.csv` file make it easier to read :)

This branch is based on #4, so that should probably be handled first. Only the last commit is relevant for this pull request.

### CODE REVIEW

**Comment by cgansen** [comment]
LGTM. Since this is a pretty trivial change, I have no qualms combining it with the other pull req, or rebasing this once that's merged.

**Review by paulsmith — CHANGES_REQUESTED** [review]
@dbrgn Can you rebase with master? I think the only changes needed now are to the README.md and `rdr.Comment`

**Comment by dbrgn** [comment]
Done!

**Review by cgansen — APPROVED** [review]
LGTM. Thanks!

**Review by paulsmith — APPROVED** [review]

**Pull request merged**
